# Generated by Django 3.1.7 on 2021-03-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0002_auto_20210327_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartprod',
            name='product',
        ),
        migrations.AddField(
            model_name='cartprod',
            name='c_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartprod',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
